/*
 * tn.h - define tokens
*/

enum tokentypes {TEOF, TLBRACE, TRBRACE, TLBRACKET, TRBRACKET, TCONST, TELSE, TIF, TINT, 
	TRETURN, TVOID, TWHILE, TPLUS, TMINUS, TSTAR, TSLASH, TMOD, TEQUAL, TNOTEQU, TLESS, TGREAT, 
	TLESSE, TGREATE, TNOT, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, 
	TMODASSIGN, TIDENT, TNUMBER, TERROR, TSEMI, TASSIGN, TLPAREN, TRPAREN, TCOMMA, TCARR,THEX, TOCT, 
	TSTRING, TCOMMENT};
